/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated/client.dashboard'
import { Route as AuthenticatedClientMissionsRouteImport } from './routes/_authenticated/client.missions'
import { Route as AuthenticatedClientProfileRouteImport } from './routes/_authenticated/client.profile'
import { Route as AuthenticatedClientSosRouteImport } from './routes/_authenticated/client.sos'
import { Route as AuthenticatedOperatorDashboardRouteImport } from './routes/_authenticated/operator.dashboard'
import { Route as AuthenticatedOperatorMissionsRouteImport } from './routes/_authenticated/operator.missions'
import { Route as AuthenticatedClientMissionIdRouteImport } from './routes/_authenticated/client.mission.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/client/dashboard',
    path: '/client/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMissionsRoute =
  AuthenticatedClientMissionsRouteImport.update({
    id: '/client/missions',
    path: '/client/missions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientProfileRoute =
  AuthenticatedClientProfileRouteImport.update({
    id: '/client/profile',
    path: '/client/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientSosRoute = AuthenticatedClientSosRouteImport.update({
  id: '/client/sos',
  path: '/client/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorDashboardRoute =
  AuthenticatedOperatorDashboardRouteImport.update({
    id: '/operator/dashboard',
    path: '/operator/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperatorMissionsRoute =
  AuthenticatedOperatorMissionsRouteImport.update({
    id: '/operator/missions',
    path: '/operator/missions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientMissionIdRoute =
  AuthenticatedClientMissionIdRouteImport.update({
    id: '/client/mission/$id',
    path: '/client/mission/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/missions': typeof AuthenticatedClientMissionsRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/sos': typeof AuthenticatedClientSosRoute
  '/operator/dashboard': typeof AuthenticatedOperatorDashboardRoute
  '/operator/missions': typeof AuthenticatedOperatorMissionsRoute
  '/client/mission/$id': typeof AuthenticatedClientMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/missions': typeof AuthenticatedClientMissionsRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/client/sos': typeof AuthenticatedClientSosRoute
  '/operator/dashboard': typeof AuthenticatedOperatorDashboardRoute
  '/operator/missions': typeof AuthenticatedOperatorMissionsRoute
  '/client/mission/$id': typeof AuthenticatedClientMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/client/missions': typeof AuthenticatedClientMissionsRoute
  '/_authenticated/client/profile': typeof AuthenticatedClientProfileRoute
  '/_authenticated/client/sos': typeof AuthenticatedClientSosRoute
  '/_authenticated/operator/dashboard': typeof AuthenticatedOperatorDashboardRoute
  '/_authenticated/operator/missions': typeof AuthenticatedOperatorMissionsRoute
  '/_authenticated/client/mission/$id': typeof AuthenticatedClientMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/client/dashboard'
    | '/client/missions'
    | '/client/profile'
    | '/client/sos'
    | '/operator/dashboard'
    | '/operator/missions'
    | '/client/mission/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/client/dashboard'
    | '/client/missions'
    | '/client/profile'
    | '/client/sos'
    | '/operator/dashboard'
    | '/operator/missions'
    | '/client/mission/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/client/dashboard'
    | '/_authenticated/client/missions'
    | '/_authenticated/client/profile'
    | '/_authenticated/client/sos'
    | '/_authenticated/operator/dashboard'
    | '/_authenticated/operator/missions'
    | '/_authenticated/client/mission/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/client/dashboard': {
      id: '/_authenticated/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/missions': {
      id: '/_authenticated/client/missions'
      path: '/client/missions'
      fullPath: '/client/missions'
      preLoaderRoute: typeof AuthenticatedClientMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/profile': {
      id: '/_authenticated/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof AuthenticatedClientProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/sos': {
      id: '/_authenticated/client/sos'
      path: '/client/sos'
      fullPath: '/client/sos'
      preLoaderRoute: typeof AuthenticatedClientSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/dashboard': {
      id: '/_authenticated/operator/dashboard'
      path: '/operator/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof AuthenticatedOperatorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator/missions': {
      id: '/_authenticated/operator/missions'
      path: '/operator/missions'
      fullPath: '/operator/missions'
      preLoaderRoute: typeof AuthenticatedOperatorMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/mission/$id': {
      id: '/_authenticated/client/mission/$id'
      path: '/client/mission/$id'
      fullPath: '/client/mission/$id'
      preLoaderRoute: typeof AuthenticatedClientMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedClientMissionsRoute: typeof AuthenticatedClientMissionsRoute
  AuthenticatedClientProfileRoute: typeof AuthenticatedClientProfileRoute
  AuthenticatedClientSosRoute: typeof AuthenticatedClientSosRoute
  AuthenticatedOperatorDashboardRoute: typeof AuthenticatedOperatorDashboardRoute
  AuthenticatedOperatorMissionsRoute: typeof AuthenticatedOperatorMissionsRoute
  AuthenticatedClientMissionIdRoute: typeof AuthenticatedClientMissionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedClientMissionsRoute: AuthenticatedClientMissionsRoute,
  AuthenticatedClientProfileRoute: AuthenticatedClientProfileRoute,
  AuthenticatedClientSosRoute: AuthenticatedClientSosRoute,
  AuthenticatedOperatorDashboardRoute: AuthenticatedOperatorDashboardRoute,
  AuthenticatedOperatorMissionsRoute: AuthenticatedOperatorMissionsRoute,
  AuthenticatedClientMissionIdRoute: AuthenticatedClientMissionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
